src/MagStore.Web/Models/Product/CreatePhotoInputModel.cs
using System.Web;

namespace MagStore.Web.Models.Product
{
    public class CreatePhotoInputModel
    {
        public string[] PhotoType { get; set; }
        public HttpPostedFileBase[] File { get; set; }
    }
}

src/MagStore.Web/Models/Product/CreateProductInputModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web;
using MagStore.Entities.Enums;

namespace MagStore.Web.Models.Product
{
    public class CreateProductInputModel : IProductPostInputModel
    {
        public string Id { get; set; }
        public string Code { get; set; }
        
        [Required(ErrorMessage = "A name must be supplied.")]
        public string Name { get; set; }

        public string Description { get; set; }
        public string Specification { get; set; }
        public string Catalogue { get; set; }
        public IEnumerable<string> Colours { get; set; }
        public IEnumerable<string> Sizes { get; set; }

        [Required(ErrorMessage="Please supply a value.")]
        [StringLength(50, MinimumLength = 4)]
        public string Gender { get; set; }

        public string Brand { get; set; }
        public string Supplier { get; set; }
        public int Rating { get; set; }
        public IEnumerable<string> Reviews { get; set; }
        public string[] PhotoType { get; set; }
        public HttpPostedFileBase[] UploadedImages { get; set; }

        [Required(ErrorMessage="The product must have a price.")]
        [Range(0.01, 10000.00, ErrorMessage = "The price must be at least 0.01")]
        public decimal Price { get; set; }

        [Required(ErrorMessage = "Please specify the product type.")]
        public ProductType ProductType { get; set; }

        public int[] AgeRange { get; set; }
        public DiscountType DiscountType { get; set; }
        public decimal DiscountAmount { get; set; }
        public IEnumerable<string> Promotions { get; set; }
        public IEnumerable<string> Tags { get; set; }
    }

    public interface IProductPostInputModel
    {
        HttpPostedFileBase[] UploadedImages { get; set; }
        string[] PhotoType { get; set; }
    }
}

src/MagStore.Web/Models/Product/CreateProductViewModel.cs
using System.Collections.Generic;
using MagStore.Entities.Enums;

namespace MagStore.Web.Models.Product
{
    public class CreateProductViewModel
    {
        public CreateProductViewModel(IEnumerable<KeyValuePair<string, string>> catalogue, IEnumerable<KeyValuePair<string, string>> promotions)
        {
            Catalogue = catalogue;
            Promotions = promotions;
        }

        public string Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Specification { get; set; }
        public IEnumerable<KeyValuePair<string, string>> Catalogue { get; set; }
        public IEnumerable<string> Colours { get; set; }
        public IEnumerable<string> Sizes { get; set; }
        public string Gender { get; set; }
        public string Brand { get; set; }
        public string Supplier { get; set; }
        public int Rating { get; set; }
        public IEnumerable<string> Reviews { get; set; }
        public IEnumerable<string> Images { get; set; }
        public decimal Price { get; set; }
        public ProductType ProductType { get; set; }
        public int[] AgeRange { get; set; }
        public DiscountType DiscountType { get; set; }
        public decimal DiscountAmount { get; set; }
        public IEnumerable<KeyValuePair<string, string>> Promotions { get; set; }
        public string Tags { get; set; }
    }
}

src/MagStore.Web/Models/Product/DeleteProductInputModel.cs
namespace MagStore.Web.Models.Product
{
    public class DeleteProductInputModel
    {
        public string Id { get; set; }
    }
}

src/MagStore.Web/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MagStore.Azure;
using MagStore.Entities;
using MagStore.Entities.Enums;
using MagStore.Infrastructure.Interfaces;
using MagStore.Web.Models.Product;

namespace MagStore.Web.Controllers
{
    public class ProductController : Controller
    {
        private readonly IShop shop;

        private readonly IStorageAccessor storageAccessor;

        private readonly ProductControllerHelper productControllerHelper;

        public ProductController(IShop shop, IStorageAccessor storageAccessor)
        {
            this.shop = shop;
            this.storageAccessor = storageAccessor;
            productControllerHelper = new ProductControllerHelper(this.shop, this.storageAccessor);
        }

        [HttpGet]
        public ActionResult CreateProduct()
        {
            var catalogues =
                shop.GetCoordinator<Catalogue>()
                    .List()
                    .Select(x => new KeyValuePair<string, string>(x.Id, x.Name));

            var promotions =
                shop.GetCoordinator<Promotion>()
                    .List()
                    .Select(x => new KeyValuePair<string, string>(x.Id, x.Name));

            return View(new CreateProductViewModel(catalogues, promotions));
        }

        [HttpPost]
        public ActionResult CreateProduct(CreateProductInputModel inputModel)
        {
            if (ModelState.IsValid)
            {
                var sizes = inputModel.Sizes;
                var products = (from c in inputModel.Colours
                                where sizes != null
                                from s in sizes
                                select new Product
                 {
                     Id = Guid.NewGuid().ToString(),
                     Code = inputModel.Code,
                     Name = inputModel.Name,
                     Description = inputModel.Description,
                     Specification = inputModel.Specification,
                     Catalogue = inputModel.Catalogue,
                     Brand = inputModel.Brand,
                     Colour = c,
                     DiscountAmount = inputModel.DiscountAmount,
                     DiscountType = inputModel.DiscountType,
                     Gender = inputModel.Gender,
                     Price = inputModel.Price,
                     ProductType = inputModel.ProductType,
                     Rating = inputModel.Rating,
                     Reviews = inputModel.Reviews,
                     Size = s,
                     Supplier = inputModel.Supplier,
                     Tags = inputModel.Tags,
                     Images =
                         inputModel.UploadedImages == null
                             ? new List<string>()
                             : CreateImages(productControllerHelper.ParseImagesFromModel(inputModel))
                 }).ToList();

                shop.GetCoordinator<Product>().Save(products);

                return RedirectToAction("EditProduct", new { id = products.First().Id });
            }

            var catalogues =
                shop.GetCoordinator<Catalogue>()
                    .List()
                    .Select(x => new KeyValuePair<string, string>(x.Id, x.Name));

            var promotions =
                shop.GetCoordinator<Promotion>()
                    .List()
                    .Select(x => new KeyValuePair<string, string>(x.Id, x.Name));

            return View(new CreateProductViewModel(catalogues, promotions));
        }

        public ActionResult ViewProducts()
        {
            return View(new ViewProductViewModel { Products = OrderedProducts() });
        }

        private IEnumerable<Product> OrderedProducts()
        {
            var enumerator = shop.GetCoordinator<Product>()
                                 .List()
                                 .OrderByDescending(p => p.Code)
                                 .ThenBy(p => p.Id)
                                 .GetEnumerator();

            while (enumerator.MoveNext())
            {
                yield return enumerator.Current;
            }
        }

        [HttpGet]
        public ActionResult EditProduct(string id)
        {
            // TODO: Sort products before pumping them out
            var product = shop.GetCoordinator<Product>().Load(id);
            var editProductViewModel = productControllerHelper.GetEditProductViewModel(product);
            return View(editProductViewModel);
        }

        [HttpPost]
        public ActionResult EditProduct(EditProductInputModel inputModel)
        {
            var product = productControllerHelper
                .MapProductModelChangesToEntity(inputModel, shop.GetCoordinator<Product>().Load(inputModel.Id));

            var existingImages = new List<KeyValuePair<string, string>>();
            if (inputModel.ExistingImages != null)
            {
                for (var i = 0; i < inputModel.ExistingImages.Count(); i++)
                {
                    var imageAndType = new KeyValuePair<string, string>
                        (
                        inputModel.ExistingImages.Skip(i).Take(1).Single(),
                        inputModel.ExistingPhotoType.Skip(i).Take(1).Single()
                        );
                    existingImages.Add(imageAndType);
                }
            }
            UpdateImages(existingImages);

            product.Images = product.Images.Union
                (
                    CreateImages(productControllerHelper.ParseImagesFromModel(inputModel))
                );
            shop.GetCoordinator<Product>().Save(product);
            return RedirectToAction("EditProduct", new { inputModel.Id }); // View(productControllerHelper.GetEditProductViewModel(product));
        }

        [HttpGet]
        public ActionResult ShowProducts(ViewProductsByCategoryInputModel inputModel)
        {
            var products = shop.GetCoordinator<Product>().List();

            var availableCategories = from a in Enum.GetValues(typeof(ProductType)).AsQueryable().OfType<ProductType>()
                                      from p in products
                                      where p.ProductType == a
                                      where p.Gender.ToUpper() == inputModel.Gender.ToUpper()
                                      select a;

            var filteredProducts = availableCategories
                .SelectMany(a => products.Where(p => p.ProductType == a))
                .AsEnumerable();

            var images = shop
                .GetCoordinator<ProductImage>()
                .Load(availableCategories
                .SelectMany(a => products
                    .Where(p => p.ProductType == a)
                    .SelectMany(p => p.Images))
                )
                .Where(i => i.ImageType == ImageType.Thumb.ToString());


            IDictionary<string, string> filters = new Dictionary<string, string>();
            filters.Add("Gender", inputModel.Gender);
            
            return View(new ProductCategoriesViewModel
            {
                Categories = availableCategories, 
                Products = filteredProducts,
                Images = images, 
                Filters = filters
            });
        }

        [HttpGet]
        public ActionResult ViewProductsByCategory(ViewProductsByCategoryInputModel inputModel)
        {
            var products =
                shop.GetCoordinator<Product>()
                    .List()
                    .Where(p => p.ProductType == (ProductType)Enum.Parse(typeof(ProductType), inputModel.Category));

            var productTypes = Enum.GetValues(typeof(ProductType)).AsQueryable().OfType<ProductType>();
            var availableCategories = from a in productTypes
                                      from p in products
                                      where p.ProductType == a
                                      where p.Gender.ToUpper() == inputModel.Gender.ToUpper()
                                      select a;

            var imagesCoordinator = shop.GetCoordinator<ProductImage>();
            var ids = availableCategories
                .SelectMany(a => products
                    .Where(p => p.ProductType == a)
                    .SelectMany(p => p.Images));

            var productImages = imagesCoordinator.Load(ids);

            var thumbs = productImages.Where(i => i.ImageType == ImageType.Thumb.ToString());

            IDictionary<string, string> filters = new Dictionary<string, string>();
            filters.Add("Category", inputModel.Category);
            filters.Add("Gender", inputModel.Gender);

            return View(new ViewProductsByCategoryViewModel { Products = products, ProductType = inputModel.Category, Images = thumbs, Filters = filters });
        }

        public ActionResult ShowProduct(ShowProductInputModel inputModel)
        {
            var productCoordinator = shop.GetCoordinator<Product>();
            var ravenQueryable = productCoordinator.List();
            var query = ravenQueryable.Where(p => p.Code == inputModel.Code);
            var productKeyValuePairs = query.Select(d => new KeyValuePair<string, Product>(d.Id, d));
            var products = productKeyValuePairs.ToList();

            var product = products.First().Value;//shop.Include<Product>(p => p.Images).Load(inputModel.Id);
            var images =
                shop.GetCoordinator<ProductImage>()
                    .Load(product.Images)
                    .Where(i => i.ImageType == ImageType.Feature.ToString());

            var availableColours = products.Select(c => c.Value.Colour);

src/MagStore.Web/Controllers/ShopController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MagStore.Azure;
using MagStore.Entities;
using MagStore.Infrastructure.Interfaces;
using MagStore.Web.Models.Shop;

namespace MagStore.Web.Controllers
{
    public class ShopController : Controller
    {
        private readonly IShop shop;
        private IStorageAccessor storageAccessor;

        public ShopController(IShop shop, IStorageAccessor storageAccessor)
        {
            this.shop = shop;
            this.storageAccessor = storageAccessor;
        }

        [Authorize(Roles = "Administrator")]
        public ActionResult Manage()
        {
            return View();
        }

        [HttpGet]
        public ActionResult UpdateCloudbird()
        {
            throw new System.NotImplementedException();
        }

        [HttpGet]
        public ActionResult UpdateAzure()
        {
            throw new System.NotImplementedException();
        }

        [HttpGet]
        public ActionResult ChangeShopSettings()
        {
            var settings = shop.GetSettings();
            var logo = new ProductImage();
            if (!string.IsNullOrEmpty(settings.Logo))
            {
                logo = shop.GetCoordinator<ProductImage>().Load(settings.Logo);
            }
            return View(new ShopSettingsViewModel(settings, logo));
        }

        [HttpPost]
        public ActionResult ChangeShopSettings(ChangeShopSettingsPostInputModel inputModel)
        {
            IShopSettings settings = shop.GetSettings();
            settings.CurrencySymbol = inputModel.CurrencySymbol;
            settings.CurrencyFormat = inputModel.CurrencyFormat;
            settings.CurrencyConversion = inputModel.CurrencyConversion;
            settings.DeliveryCharge = inputModel.DeliveryCharge;
            settings.Name = inputModel.Name;
            settings.TagLine = inputModel.TagLine;

            settings.Logo = inputModel.Logo == null
                                ? string.Empty
                                : CreateImages(new[]
                                {
                                    new KeyValuePair<string, HttpPostedFileBase>("Thumb", inputModel.Logo)
                                })
                                .First();

            shop.UpdateSettings(settings);
            return RedirectToAction("ChangeShopSettings");
        }

        public ActionResult DeleteLogoFromSettings(DeleteLogoFromSettingsPostInputModel inputModel)
        {
            var settings = shop.GetSettings();

            settings.Logo = string.Empty;

            shop.UpdateSettings(settings);

            return RedirectToAction("ChangeShopSettings");
        }

        private IEnumerable<string> CreateImages(IEnumerable<KeyValuePair<string, HttpPostedFileBase>> images)
        {
            var result = new List<string>();
            foreach (var image in images)
            {
                var id = Guid.NewGuid().ToString();
                CreateImage(image.Value, image.Key, id);
                result.Add(id);
            }
            return result;
        }

        private void CreateImage(HttpPostedFileBase image, string imageType, string fileName)
        {
            var inputStream = image.InputStream;
            var uri = storageAccessor.AddBlobToResource(fileName, inputStream);

            var img = new ProductImage
            {
                Id = fileName,
                ImageType = imageType,
                ImageUrl = uri.ToString()
            };
            shop.GetCoordinator<ProductImage>().Save(img);
        }
    }
}

src/MagStore.Web/Views/Product/CreateProduct.cshtml
@using MagStore.Entities.Additives
@using MagStore.Entities.Enums
@model MagStore.Web.Models.Product.CreateProductViewModel

@{
    ViewBag.Title = "CreateProduct";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section ReadyScripts
{
    $("input#addPhoto").click(function() { 
        $("#photographs").append('<div style="border: solid 1px blue; margin: 3px 3px 3px 3px; padding: 3px 3px 3px 3px;">
            ' + 
            '<b>Attach an image to this product and specify the type of image:</b><br />
            ' +
            '<select name="PhotoType">' + '<option value="Thumb">Thumb</option>
                ' + 
            '<option value="Feature">Feature</option>
                ' + 
            '<option value="HiRes">HiRes</option>
                ' + 
            '</select><br />
            <br />
            ' + 
            '<input type="file" name="UploadedImages" id="Photo" />
    </div>
');
     });
}
@section Scripts
{
    <link href="~/Content/css/style.css" rel="stylesheet" type="text/css" />
    <link href='http://fonts.googleapis.com/css?family=Signika:400,700|Norican' rel='stylesheet'
        type='text/css' />
    <!--[if lt IE 9]><script src="js/html5shiv.js"></script><![endif]-->
    <script type="text/javascript" src="~/Content/js/jquery-1.7.2.min.js"></script>
    <script type="text/javascript" src="~/Content/js/jquery-ui-1.8.21.custom.min.js"></script>
    <script type="text/javascript" src="~/Content/js/jquery.menu.pack.js"></script>
    <script type="text/javascript" src="~/Content/js/hover.zoom.js"></script>
    <script type="text/javascript" src="~/Content/js/settings-inner.js"></script>
}
<!-- MAIN CONTENT START -->
<section class="main wrapper">
    <div id="breadcrumb">
        @Html.ActionLink("Manage Shop", "Manage", "Shop") / Create Product
    </div>
    <article>
        <h1>Create Product</h1>
        @{
            var form = Html.BeginForm("CreateProduct", "Product", FormMethod.Post, new { enctype = "multipart/form-data" });

            @Html.ValidationSummary(true);

            <fieldset>
                <div class="editor-label">
                    @Html.LabelFor(model => model.Code)
                </div>
                <div class="editor-field">
                    @Html.EditorFor(model => model.Code)
                    @Html.ValidationMessageFor(model => model.Code)
                </div>

                <div class="editor-label">
                    @Html.LabelFor(model => model.Name)
                </div>
                <div class="editor-field">
                    @Html.EditorFor(model => model.Name)
                    @Html.ValidationMessageFor(model => model.Name)
                </div>

                <div class="editor-label">
                    @Html.LabelFor(model => model.Description)
                </div>
                <div class="editor-field">
                    @Html.TextArea("Description", Model.Description, new { Name = "Description" })
                    @Html.ValidationMessageFor(model => model.Description)
                </div>

                <div class="editor-label">
                    @Html.LabelFor(model => model.Specification)
                </div>
                <div class="editor-field">
                    @Html.TextArea("Description", Model.Specification, new { Name = "Specification" })
                    @Html.ValidationMessageFor(model => model.Specification)
                </div>

                <div class="editor-label">
                    @Html.LabelFor(model => model.Catalogue)
                </div>
                <div class="editor-field">
                    @Html.DropDownList("Catalogue", Model.Catalogue.Select(x => new SelectListItem { Selected = false, Text = x.Value, Value = x.Key }), new { name = "Catalogue" })
                    @Html.ValidationMessageFor(model => model.Catalogue)
                </div>

                @if (Model.Promotions.Any())
                {
                    <div class="editor-label">
                        @Html.LabelFor(model => model.Promotions)
                    </div>
                    <div class="editor-field">
                        @Html.ListBox("Promotions", Model.Promotions.Select(x => new SelectListItem { Selected = false, Text = x.Value, Value = x.Key }), new { name = "Promotions" })
                        @Html.ValidationMessageFor(model => model.Promotions)
                    </div>
                }
                <div class="editor-label">
                    @Html.LabelFor(model => model.Colours)
                </div>
                <div class="editor-field">
                    <select id="Colours" multiple="multiple" name="Colours" style="width: 200px; height: 140px;">
                        @foreach (var c in new Colours())
                        {
                            <option value="@c.Key" style="background-color: @c.Value">@c.Key</option>
                        }
                    </select>
                    @Html.ValidationMessageFor(model => model.Colours)
                </div>

                <div class="editor-label">
                    @Html.LabelFor(model => model.Gender)
                </div>
                <div class="editor-field">
                    @Html.DropDownList("Gender", new List<SelectListItem>
                        {
                            new SelectListItem {Selected = true, Value = "", Text = "" }, 
                            new SelectListItem {Text = "Male",Value = "Male"}, 
                            new SelectListItem {Text = "Female", Value = "Female"}
                        })
                </div>

                <div class="editor-label">
                    @Html.LabelFor(model => model.Sizes)
                </div>
                <div class="editor-field">
                    <select id="Sizes" multiple="multiple" name="Sizes" style="width: 200px; height: 140px;">
                        @foreach (var c in new Sizes())
                        {
                            <option value="@c">@c</option>
                        }
                    </select>
                    @Html.ValidationMessageFor(model => model.Sizes)
                </div>

                <div class="editor-label">
                    @Html.LabelFor(model => model.Brand)
                </div>
                <div class="editor-field">
                    @Html.EditorFor(model => model.Brand)
                    @Html.ValidationMessageFor(model => model.Brand)
                </div>

                <div class="editor-label">
                    @Html.LabelFor(model => model.ProductType)
                </div>
                <div class="editor-field">

                    @{
                        var productTypes = new List<SelectListItem>();

                        productTypes
                            .AddRange(Enum.GetNames(typeof(ProductType))
                            .Select(x => new SelectListItem
                                {
                                    Text = x,
                                    Value = x
                                }));
                                
                    }
                    @Html.DropDownListFor(model => model.ProductType, productTypes)

                    @*                    @Html.ValidationMessageFor(model => model.ProductType)*@
                </div>

                <div class="editor-label">
                    @Html.LabelFor(model => model.Supplier)
                </div>
                <div class="editor-field">
                    @Html.EditorFor(model => model.Supplier)
                    @Html.ValidationMessageFor(model => model.Supplier)
                </div>

                <div class="editor-label">
                    @Html.LabelFor(model => model.Rating)
                </div>
                <div class="editor-field">
                    @Html.EditorFor(model => model.Rating)
                    @Html.ValidationMessageFor(model => model.Rating)
                </div>

                <div class="editor-label">
                    @Html.LabelFor(model => model.Price)
                </div>
                <div class="editor-field">
                    @Html.EditorFor(model => model.Price)
                    @Html.ValidationMessageFor(model => model.Price)
                </div>

                <div class="editor-label">
                    @Html.LabelFor(model => model.DiscountAmount)
                </div>
                <div class="editor-field">
                    @Html.EditorFor(model => model.DiscountAmount)
                    @Html.ValidationMessageFor(model => model.DiscountAmount)
                </div>
                <div class="editor-label">
                    @Html.LabelFor(model => model.Tags)
                </div>
                <div class="editor-field">
                    @Html.EditorFor(model => model.Tags)
                </div>
                <p id="photographs"></p>
                <br />
                <input type="button" style="border: solid 1px green; padding: 2px;" id="addPhoto" value="Add Photo" />
                <p>
                    <input type="submit" value="Create" />
                </p>
            </fieldset>
            form.EndForm();
        }
    </article>

    <aside>

        <section class="categories">
            <h2>About This Theme</h2>
            <div class="accordion">
                <h3><a href="#">Typography</a></h3>
                <div>
                    <ul>
                        <li><a href="typography.html">Submenu 1</a></li>
                        <li><a href="typography.html">Submenu 2</a></li>
                        <li><a href="typography.html">Submenu 3</a></li>
                    </ul>
                </div>
                <h3><a href="#">Columns &amp; Buttons</a></h3>
                <div>
                    <ul>
                        <li><a href="columns.html">Submenu 1</a></li>
                        <li><a href="columns.html">Submenu 2</a></li>
                        <li><a href="columns.html">Submenu 3</a></li>
                    </ul>
                </div>
                <h3><a href="#">Tables</a></h3>
                <div>
                    <ul>
                        <li><a href="tables.html">Submenu 1</a></li>
                        <li><a href="tables.html">Submenu 2</a></li>
                        <li><a href="tables.html">Submenu 3</a></li>
                    </ul>
                </div>
                <h3><a href="#">Pricing Table</a></h3>
                <div>
                    <ul>
                        <li><a href="pricing.html">Submenu 1</a></li>
                        <li><a href="pricing.html">Submenu 2</a></li>
                        <li><a href="pricing.html">Submenu 3</a></li>
                    </ul>
                </div>
                <h3><a href="#">Tabs &amp; Accordion</a></h3>
                <div>
                    <ul>
                        <li><a href="tabs.html">Submenu 1</a></li>
                        <li><a href="tabs.html">Submenu 2</a></li>
                        <li><a href="tabs.html">Submenu 3</a></li>
                    </ul>
                </div>
            </div>
            <!-- .accordion end -->
        </section>
        <!-- .categories end -->

        <section class="about">
            <h2>About Us</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla ac massa nulla, sed laoreet tellus. Proin feugiat rhoncus massa in faucibus. Duis et orci nunc. Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
            <p><a href="about.html" class="more">Read More</a></p>
            <p>&nbsp;</p>
        </section>
        <!-- .about end -->

    </aside>

    <div class="clear"></div>

</section>
<!-- .main end -->
<!-- MAIN CONTENT END -->

src/MagStore.Web/Views/Product/EditProduct11.cshtml
@model dynamic

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>title</h2>

src/MagStore.Web/Views/Product/ListPhotos.cshtml
@model dynamic

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
    <head>
        <title>title</title>
    </head>
    <body>
        <div>
              @{
                  if (ViewBag.Photos != null)
                  {
                      foreach (var photo in ViewBag.Photos)
                      {
                          <img src="@photo.Uri"/><br />
                      }
                  }
              }
        </div>
    </body>
</html>

src/MagStore.Web/Views/Product/PhotoPartial.cshtml
@model dynamic
<select name="PhotoType">
    <option value="Thumb">Thumb</option>
    <option value="Feature">Feature</option>
    <option value="HiRes">HiRes</option>
</select>
<input type="file" name="UploadedImages" id="Photo" />
<br />

src/MagStore.Web/Views/Product/_EditProductButton.cshtml
                @{
                    if (User.IsInRole("Administrator"))
                    {
                        using (Html.BeginForm("EditProduct", "Product", FormMethod.Get))
                        {
                            <input type="hidden" name="Id" value="@Model.Product.Id"/>
                            <input type="submit" value="Edit this product"/>
                        }
                    }
                }