src/MagStore.Web/Controllers/ImagesController.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MagStore.Azure;
using MagStore.Entities;
using MagStore.Entities.Enums;
using MagStore.Infrastructure.Interfaces;

namespace MagStore.Web.Controllers
{
    public class ImagesController : Controller
    {
        private readonly IShop shop;
        private readonly IStorageAccessor storageAccessor;

        public ImagesController(IShop shop, IStorageAccessor storageAccessor)
        {
            this.shop = shop;
            this.storageAccessor = storageAccessor;
        }

        [HttpGet]
        public ActionResult CreateImage()
        {
            return View(new ImageCreationGetModel());
        }

        [HttpGet]
        public ActionResult EditImage(ImageEditGetInputModel getInputModel)
        {
            var image = shop.GetCoordinator<ProductImage>()
                            .Load(getInputModel.Id);

            return View(new EditImageViewModel { Image = image });
        }

        [HttpPost]
        public ActionResult CreateImage(ImageCreationPostModel postModel)
        {
            //ValidateModel(postModel);
            var fileName = Guid.NewGuid().ToString();
            if (ModelState.IsValid)
            {
                CreateImage(postModel.Image, postModel.ImageType.ToString(), fileName);
            }
            return RedirectToAction("EditImage", new { Id = fileName }); //View(new ImageCreationGetModel());
        }

        [HttpPost]
        public ActionResult EditImage(ImageEditPostModel postModel)
        {
            if (ModelState.IsValid)
            {
                var fileName = postModel.Id;
                UpdateImage(postModel, fileName);
            }

            return RedirectToAction( "EditImage", new {postModel.Id }); //View(new ImageEditGetInputModel());
        }

        [HttpGet]
        public ActionResult DeleteImageFromProduct(string productId, string imageId)
        {
            var product = shop.GetCoordinator<Product>().Load(productId);
            product.Images = product.Images.Except(new[] {imageId});
            shop.GetCoordinator<Product>().Save(product);
            
            return RedirectToAction("EditProduct", "Product", new { Id = productId });
        }

        private void CreateImage(HttpPostedFileBase image, string imageType, string fileName)
        {
            var inputStream = image.InputStream;
            var uri = storageAccessor.AddBlobToResource(fileName, inputStream);

            var img = new ProductImage
                {
                    Id = fileName,
                    ImageType = imageType,
                    ImageUrl = uri.ToString()
                };
            shop.GetCoordinator<ProductImage>().Save(img);
        }

        private void UpdateImage(ImageEditPostModel postModel, string fileName)
        {
            var hasChanges = postModel.Image != null;
            Uri uri = null;
            if (hasChanges)
            {
                var inputStream = postModel.Image.InputStream;
                uri = storageAccessor.AddBlobToResource(fileName, inputStream);
            }

            var image = shop.GetCoordinator<ProductImage>().Load(postModel.Id);
            image.ImageType = postModel.ImageType.ToString();
            if (uri != null) image.ImageUrl = uri.ToString();
            shop.GetCoordinator<ProductImage>()
                .Save(image);
        }
    }

    public class ImageEditGetInputModel
    {
        public string Id { get; set; }
    }

    public class EditImageViewModel
    {
        public ProductImage Image { get; set; }
        public IEnumerable<string> ImageTypes { get { return new[] { "" }.Union(Enum.GetNames(typeof(ImageType))); } }
    }

    public class ImageEditPostModel : ImageCreationPostModel
    {
        public string Id { get; set; }
    }

    public class ImageCreationPostModel
    {
        [Required(AllowEmptyStrings = false, ErrorMessage = "Please select a image type.")]
        public ImageType ImageType { get; set; }
        public HttpPostedFileBase Image { get; set; }
    }

    public class ImageCreationGetModel
    {
        public IEnumerable<string> ImageTypes { get { return new[] { "" }.Union(Enum.GetNames(typeof(ImageType))); } }
    }
}

src/MagStore.Web/Views/Images/CreateImage.cshtml
@model MagStore.Web.Controllers.ImageCreationGetModel

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
    <head>
        <title>Create Image</title>
    </head>
    <body>
        @using (Html.BeginForm("CreateImage", "Images", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            Html.ValidationSummary(true);
            <div>
                ImageType:
            </div>
            <div>
              @Html.DropDownListFor(model => model.ImageTypes, Model.ImageTypes.Select(x => new SelectListItem { Text = x, Value = x }), new { Name = "ImageType" })
              @Html.ValidationMessageFor(model => model.ImageTypes)
            </div>
            <div>
              Image to upload:
            </div>
            <div>
                <input type="file" name="Image" />
            </div>
            <div>
                <input type="submit" />
            </div>
        }
        <img src="http://magshopstrg.blob.core.windows.net/resources/08a8edfe-6465-4cf1-a586-85672ed8c579"/>
    </body>
</html>

src/MagStore.Web/Views/Images/EditImage.cshtml
@model MagStore.Web.Controllers.EditImageViewModel

@{
    Layout = null;
}

<!DOCTYPE html>

@{
    ViewBag.Title = "Edit Image";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Scripts
{
    <link href="~/Content/css/style.css" rel="stylesheet" type="text/css" />
    <link href='http://fonts.googleapis.com/css?family=Signika:400,700|Norican' rel='stylesheet'
        type='text/css' />
    <!--[if lt IE 9]><script src="js/html5shiv.js"></script><![endif]-->
    <script type="text/javascript" src="~/Content/js/jquery-1.7.2.min.js"></script>
    <script type="text/javascript" src="~/Content/js/jquery-ui-1.8.21.custom.min.js"></script>
    <script type="text/javascript" src="~/Content/js/jquery.menu.pack.js"></script>
    <script type="text/javascript" src="~/Content/js/hover.zoom.js"></script>
    <script type="text/javascript" src="~/Content/js/settings-inner.js"></script>
}
<!-- MAIN CONTENT START -->
<section class="main wrapper">
    <article>
        <h1>Edit Image</h1>
        @using (Html.BeginForm("EditImage", "Images", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <div>
                Id:
                <br />
                @Model.Image.Id
                <br />
                Image Type:
                <br />
                @Html.DropDownListFor(model => model.Image.ImageType, Model.ImageTypes.Select(t => new SelectListItem {Text = t, Value = t}),new { Name = "ImageType" })
                <br />
                Current Image:
                <br />
                <img src="@Model.Image.ImageUrl" alt="" />
                <br />
                Change:
                <br/>
                <input type="file" name="Image" />
                <br />
                <input type="submit" />
            </div>
        }
    </article>
        <aside>
		
        <section class="categories">
            <h2>About This Theme</h2>
            <div class="accordion">
                <h3><a href="#">Typography</a></h3>
                <div>
                    <ul>
                        <li><a href="typography.html">Submenu 1</a></li>
                        <li><a href="typography.html">Submenu 2</a></li>
                        <li><a href="typography.html">Submenu 3</a></li>
                    </ul>
                </div>
                <h3><a href="#">Columns &amp; Buttons</a></h3>
                <div>
                    <ul>
                        <li><a href="columns.html">Submenu 1</a></li>
                        <li><a href="columns.html">Submenu 2</a></li>
                        <li><a href="columns.html">Submenu 3</a></li>
                    </ul>
                </div>
                <h3><a href="#">Tables</a></h3>
                <div>
                    <ul>
                        <li><a href="tables.html">Submenu 1</a></li>
                        <li><a href="tables.html">Submenu 2</a></li>
                        <li><a href="tables.html">Submenu 3</a></li>
                    </ul>
                </div>
                <h3><a href="#">Pricing Table</a></h3>
                <div>
                    <ul>
                        <li><a href="pricing.html">Submenu 1</a></li>
                        <li><a href="pricing.html">Submenu 2</a></li>
                        <li><a href="pricing.html">Submenu 3</a></li>
                    </ul>
                </div>
                <h3><a href="#">Tabs &amp; Accordion</a></h3>
                <div>
                    <ul>
                        <li><a href="tabs.html">Submenu 1</a></li>
                        <li><a href="tabs.html">Submenu 2</a></li>
                        <li><a href="tabs.html">Submenu 3</a></li>
                    </ul>
                </div>
            </div><!-- .accordion end -->
        </section><!-- .categories end -->
			
        <section class="about">
            <h2>About Us</h2>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla ac massa nulla, sed laoreet tellus. Proin feugiat rhoncus massa in faucibus. Duis et orci nunc. Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
            <p><a href="about.html" class="more">Read More</a></p>
            <p>&nbsp;</p>
        </section><!-- .about end -->
		
    </aside>
		
    <div class="clear"></div>

</section>